import type { Vocabulary, ReadingQuestion } from "./database.types";

// MVP용 로컬 샘플 데이터 (Supabase 연결 전에도 작동)
export const sampleVocabularies: Omit<Vocabulary, "id" | "created_at">[] = [
  // N4
  { word: "勉強", reading: "べんきょう", meaning: "공부", level: "N4", example: "日本語を勉強します。" },
  { word: "旅行", reading: "りょこう", meaning: "여행", level: "N4", example: "旅行に行きます。" },
  { word: "病気", reading: "びょうき", meaning: "병, 질병", level: "N4", example: "病気になりました。" },
  { word: "準備", reading: "じゅんび", meaning: "준비", level: "N4", example: "試験の準備をします。" },
  { word: "経験", reading: "けいけん", meaning: "경험", level: "N4", example: "いい経験になりました。" },
  { word: "趣味", reading: "しゅみ", meaning: "취미", level: "N4", example: "趣味は読書です。" },
  { word: "約束", reading: "やくそく", meaning: "약속", level: "N4", example: "友だちと約束しました。" },
  { word: "説明", reading: "せつめい", meaning: "설명", level: "N4", example: "先生が説明してくれました。" },
  { word: "注意", reading: "ちゅうい", meaning: "주의", level: "N4", example: "注意してください。" },
  { word: "連絡", reading: "れんらく", meaning: "연락", level: "N4", example: "後で連絡します。" },
  { word: "相談", reading: "そうだん", meaning: "상담", level: "N4", example: "先生に相談しました。" },
  { word: "出発", reading: "しゅっぱつ", meaning: "출발", level: "N4", example: "朝6時に出発します。" },
  { word: "到着", reading: "とうちゃく", meaning: "도착", level: "N4", example: "空港に到着しました。" },
  { word: "予定", reading: "よてい", meaning: "예정", level: "N4", example: "明日の予定は何ですか。" },
  { word: "安全", reading: "あんぜん", meaning: "안전", level: "N4", example: "安全に気をつけてください。" },
  { word: "失敗", reading: "しっぱい", meaning: "실패", level: "N4", example: "試験に失敗しました。" },
  { word: "成功", reading: "せいこう", meaning: "성공", level: "N4", example: "やっと成功しました。" },
  { word: "反対", reading: "はんたい", meaning: "반대", level: "N4", example: "彼は反対しました。" },
  { word: "心配", reading: "しんぱい", meaning: "걱정", level: "N4", example: "心配しないでください。" },
  { word: "自由", reading: "じゆう", meaning: "자유", level: "N4", example: "自由に使ってください。" },
  // N3
  { word: "影響", reading: "えいきょう", meaning: "영향", level: "N3", example: "環境に影響を与える。" },
  { word: "態度", reading: "たいど", meaning: "태도", level: "N3", example: "彼の態度が変わった。" },
  { word: "状況", reading: "じょうきょう", meaning: "상황", level: "N3", example: "現在の状況を説明します。" },
  { word: "関係", reading: "かんけい", meaning: "관계", level: "N3", example: "二人の関係は良好です。" },
  { word: "原因", reading: "げんいん", meaning: "원인", level: "N3", example: "事故の原因を調べる。" },
  { word: "結果", reading: "けっか", meaning: "결과", level: "N3", example: "試験の結果が出ました。" },
  { word: "判断", reading: "はんだん", meaning: "판단", level: "N3", example: "正しい判断をする。" },
  { word: "責任", reading: "せきにん", meaning: "책임", level: "N3", example: "責任を持って行動する。" },
  { word: "経済", reading: "けいざい", meaning: "경제", level: "N3", example: "経済が成長している。" },
  { word: "政治", reading: "せいじ", meaning: "정치", level: "N3", example: "政治に興味がある。" },
  { word: "環境", reading: "かんきょう", meaning: "환경", level: "N3", example: "環境を守りましょう。" },
  { word: "技術", reading: "ぎじゅつ", meaning: "기술", level: "N3", example: "新しい技術を学ぶ。" },
  { word: "制度", reading: "せいど", meaning: "제도", level: "N3", example: "教育制度を改革する。" },
  { word: "対象", reading: "たいしょう", meaning: "대상", level: "N3", example: "子どもが対象です。" },
  { word: "基本", reading: "きほん", meaning: "기본", level: "N3", example: "基本を大切にする。" },
  { word: "条件", reading: "じょうけん", meaning: "조건", level: "N3", example: "条件を確認してください。" },
  { word: "効果", reading: "こうか", meaning: "효과", level: "N3", example: "薬の効果が出た。" },
  { word: "目的", reading: "もくてき", meaning: "목적", level: "N3", example: "旅行の目的は何ですか。" },
  { word: "意見", reading: "いけん", meaning: "의견", level: "N3", example: "意見を聞かせてください。" },
  { word: "表現", reading: "ひょうげん", meaning: "표현", level: "N3", example: "日本語の表現を学ぶ。" },
];

export const sampleReadingQuestions: Omit<ReadingQuestion, "id" | "created_at">[] = [
  // N4
  {
    level: "N4",
    passage: "田中さんは毎朝6時に起きます。朝ごはんを食べてから、電車で会社に行きます。会社は9時から5時までです。帰りにスーパーで買い物をして、家で晩ごはんを作ります。",
    question: "田中さんは会社にどうやって行きますか？",
    choices: ["バスで行きます", "電車で行きます", "歩いて行きます", "車で行きます"],
    correct_answer: "電車で行きます",
    explanation: "지문에 '電車で会社に行きます'라고 적혀 있습니다.",
    difficulty: 1,
  },
  {
    level: "N4",
    passage: "来週の日曜日に友だちとピクニックに行きます。天気がよければ公園で弁当を食べます。雨だったら映画を見に行きます。",
    question: "雨が降ったらどうしますか？",
    choices: ["家にいます", "ピクニックに行きます", "映画を見に行きます", "買い物をします"],
    correct_answer: "映画を見に行きます",
    explanation: "'雨だったら映画を見に行きます'라고 했습니다.",
    difficulty: 1,
  },
  {
    level: "N4",
    passage: "私の町には大きい図書館があります。毎週土曜日に本を借りに行きます。図書館で勉強することもあります。静かで、とてもいいところです。",
    question: "この人は図書館で何をしますか？",
    choices: ["本を買います", "本を借りたり勉強したりします", "友だちと話します", "音楽を聞きます"],
    correct_answer: "本を借りたり勉強したりします",
    explanation: "'本を借りに行きます'と'勉強することもあります'から、両方行うことが分かります。",
    difficulty: 2,
  },
  {
    level: "N4",
    passage: "山田さんは去年から日本語を勉強しています。毎日2時間勉強します。来月JLPT N4の試験を受けます。合格したいので、頑張っています。",
    question: "山田さんはどのくらい日本語を勉強していますか？",
    choices: ["半年", "1年くらい", "2年", "3年"],
    correct_answer: "1年くらい",
    explanation: "'去年から'勉強しているので、約1年です。",
    difficulty: 2,
  },
  {
    level: "N4",
    passage: "日本の夏はとても暑いです。7月と8月が一番暑いです。エアコンがないと大変です。でも、夏祭りや花火大会があって楽しいです。",
    question: "日本の夏について正しいのはどれですか？",
    choices: ["涼しいです", "祭りがあって楽しいです", "雨が多いです", "寒いです"],
    correct_answer: "祭りがあって楽しいです",
    explanation: "'夏祭りや花火大会があって楽しい'と書いてあります。",
    difficulty: 2,
  },
  // N3
  {
    level: "N3",
    passage: "最近、テレワークをする人が増えています。通勤時間がなくなるので、自由な時間が増えます。しかし、家で働くと仕事と生活の区別がつきにくくなるという問題もあります。",
    question: "テレワークの問題点は何ですか？",
    choices: [
      "通勤時間が長い",
      "仕事と生活の区別がつきにくい",
      "給料が減る",
      "同僚と会えない",
    ],
    correct_answer: "仕事と生活の区別がつきにくい",
    explanation: "'仕事と生活の区別がつきにくくなる'と問題点として述べられています。",
    difficulty: 2,
  },
  {
    level: "N3",
    passage: "日本では、電車の中で電話をするのはマナー違反とされています。周りの人に迷惑をかけるからです。メールやメッセージなら問題ありませんが、通話は控えるべきです。",
    question: "電車の中でしてはいけないことは何ですか？",
    choices: ["メールをすること", "電話をすること", "本を読むこと", "音楽を聞くこと"],
    correct_answer: "電話をすること",
    explanation: "'電車の中で電話をするのはマナー違反'と明記されています。",
    difficulty: 2,
  },
  {
    level: "N3",
    passage: "健康のために運動を始めようと思って、ジムに入会しました。最初は週に3回通っていましたが、仕事が忙しくなって、今は週1回しか行けません。それでも、行かないよりはましだと思っています。",
    question: "この人は今、どのくらいジムに行っていますか？",
    choices: ["毎日", "週に3回", "週に1回", "月に1回"],
    correct_answer: "週に1回",
    explanation: "'今は週1回しか行けません'と書いてあります。",
    difficulty: 2,
  },
  {
    level: "N3",
    passage: "最近の若者は本を読まなくなったと言われています。しかし、実際にはスマートフォンで電子書籍を読んでいる人も多いです。読書の形が変わっただけで、読んでいないわけではありません。",
    question: "この文章で筆者が言いたいことは何ですか？",
    choices: [
      "若者は本を読まない",
      "電子書籍は良くない",
      "読書の形が変わっただけだ",
      "スマホは悪い影響がある",
    ],
    correct_answer: "読書の形が変わっただけだ",
    explanation: "'読書の形が変わっただけで、読んでいないわけではない'が筆者の主張です。",
    difficulty: 3,
  },
  {
    level: "N3",
    passage: "日本語の敬語は、大きく分けて三つあります。「尊敬語」は相手の動作を高める言い方、「謙譲語」は自分の動作を低くする言い方、「丁寧語」は「です・ます」のような丁寧な言い方です。外国人にとって敬語は難しいですが、ビジネスでは必要です。",
    question: "「謙譲語」とはどのような言い方ですか？",
    choices: [
      "相手を高める言い方",
      "自分を低くする言い方",
      "丁寧な言い方",
      "カジュアルな言い方",
    ],
    correct_answer: "自分を低くする言い方",
    explanation: "'謙譲語は自分の動作を低くする言い方'と定義されています。",
    difficulty: 3,
  },
];
